library(shiny)
library(shinyMatrix)
library(grid)
library(gridExtra)
library(reshape2)
library(DT)
library(png)
library(tools)
setwd("C:/Users/lucy_/covid-recovery/")

source("app/ui.R")
source("app/server.R")
source("app/src.R")

shinyApp(ui = ui, server = server)
